import { ActionTag } from './types';
import type { ActionDef, ActionType } from './types';

/**
 * v5 action registry — all actions now have targetType and tool fields.
 * baseEnergyCost is the floor; actual cost computed per-organism in action-factory.ts.
 */
export const ACTION_REGISTRY: ReadonlyMap<ActionType, ActionDef> = new Map<ActionType, ActionDef>([
  ['talk', {
    type: 'talk',
    tags: new Set([ActionTag.SOCIAL]),
    baseEnergyCost: 0.2,
    durationRange: [2340, 4680],
    requiresTarget: true,
    targetType: 'external_cell',
    targetRange: 1,
    interruptible: true,
    tool: null,
  }],
  ['quarrel', {
    type: 'quarrel',
    tags: new Set([ActionTag.SOCIAL, ActionTag.COMBAT]),
    baseEnergyCost: 0.4,
    durationRange: [2340, 4680],
    requiresTarget: true,
    targetType: 'external_cell',
    targetRange: 1,
    interruptible: true,
    tool: null,
  }],
  ['attack', {
    type: 'attack',
    tags: new Set([ActionTag.COMBAT]),
    baseEnergyCost: 0.4,
    durationRange: [1170, 2340],
    requiresTarget: true,
    targetType: 'external_cell',
    targetRange: 2,
    interruptible: false,
    tool: '⚔️',
  }],
  ['hunt', {
    type: 'hunt',
    tags: new Set([ActionTag.COMBAT, ActionTag.RESOURCE]),
    baseEnergyCost: 0.5,
    durationRange: [1500, 2600],
    requiresTarget: true,
    targetType: 'external_cell',
    targetRange: 2,
    interruptible: false,
    tool: '⚔️',
  }],
  ['heal', {
    type: 'heal',
    tags: new Set([ActionTag.SOCIAL, ActionTag.HELPFUL]),
    baseEnergyCost: 1.5,
    durationRange: [2340, 4680],
    requiresTarget: true,
    targetType: 'external_cell',
    targetRange: 1,
    interruptible: true,
    tool: '💊',
  }],
  ['share', {
    type: 'share',
    tags: new Set([ActionTag.SOCIAL, ActionTag.HELPFUL]),
    baseEnergyCost: 0.4,
    durationRange: [780, 1300],
    requiresTarget: true,
    targetType: 'external_cell',
    targetRange: 1,
    interruptible: true,
    tool: null,
  }],
  ['reproduce', {
    type: 'reproduce',
    tags: new Set([ActionTag.SOCIAL]),
    baseEnergyCost: 1.5,
    durationRange: [5200, 8320],
    requiresTarget: true,
    targetType: 'external_cell',
    targetRange: 1,
    interruptible: false,
    tool: null,
  }],
  ['sleep', {
    type: 'sleep',
    tags: new Set([ActionTag.SURVIVAL]),
    baseEnergyCost: 0,
    durationRange: [20800, 31200],
    requiresTarget: false,
    targetType: 'self',
    targetRange: 0,
    interruptible: true,
    tool: null,
  }],
  ['harvest', {
    type: 'harvest',
    tags: new Set([ActionTag.RESOURCE]),
    baseEnergyCost: 0.25,
    durationRange: [1560, 3900],
    requiresTarget: true,
    targetType: 'external_cell',
    targetRange: 1,
    interruptible: false,
    tool: '✋',
  }],
  ['eat', {
    type: 'eat',
    tags: new Set([ActionTag.SURVIVAL]),
    baseEnergyCost: 0,
    durationRange: [780, 1300],
    requiresTarget: false,
    targetType: 'self',
    targetRange: 0,
    interruptible: false,
    tool: null,
  }],
  ['drink', {
    type: 'drink',
    tags: new Set([ActionTag.SURVIVAL]),
    baseEnergyCost: 0,
    durationRange: [780, 1300],
    requiresTarget: false,
    targetType: 'self',
    targetRange: 1,
    interruptible: false,
    tool: null,
  }],
  ['drink_saltwater', {
    type: 'drink_saltwater',
    tags: new Set([ActionTag.SURVIVAL]),
    baseEnergyCost: 0.05,
    durationRange: [2000, 3000],
    requiresTarget: false,
    targetType: 'self',
    targetRange: 0,
    interruptible: true,
    tool: null,
  }],
  ['wash', {
    type: 'wash',
    tags: new Set([ActionTag.SURVIVAL, ActionTag.HYGIENE]),
    baseEnergyCost: 0,
    durationRange: [780, 1300],
    requiresTarget: false,
    targetType: 'self',
    targetRange: 0,
    interruptible: false,
    tool: null,
  }],
  ['deposit', {
    type: 'deposit',
    tags: new Set([ActionTag.RESOURCE, ActionTag.FACTION]),
    baseEnergyCost: 0,
    durationRange: [780, 1300],
    requiresTarget: false,
    targetType: 'none',
    targetRange: 1,
    interruptible: false,
    tool: null,
  }],
  ['withdraw', {
    type: 'withdraw',
    tags: new Set([ActionTag.RESOURCE, ActionTag.FACTION]),
    baseEnergyCost: 0,
    durationRange: [780, 1300],
    requiresTarget: false,
    targetType: 'none',
    targetRange: 1,
    interruptible: false,
    tool: null,
  }],
  ['pickup', {
    type: 'pickup',
    tags: new Set([ActionTag.RESOURCE]),
    baseEnergyCost: 0,
    durationRange: [780, 1300],
    requiresTarget: false,
    targetType: 'none',
    targetRange: 1,
    interruptible: false,
    tool: null,
  }],
  ['poop', {
    type: 'poop',
    tags: new Set([ActionTag.HYGIENE]),
    baseEnergyCost: 0,
    durationRange: [1300, 2600],
    requiresTarget: false,
    targetType: 'self',
    targetRange: 0,
    interruptible: false,
    tool: null,
  }],
  ['clean', {
    type: 'clean',
    tags: new Set([ActionTag.HYGIENE, ActionTag.LEISURE]),
    baseEnergyCost: 0.25,
    durationRange: [2080, 3120],
    requiresTarget: false,
    targetType: 'none',
    targetRange: 1,
    interruptible: false,
    tool: null,
  }],
  ['play', {
    type: 'play',
    tags: new Set([ActionTag.LEISURE]),
    baseEnergyCost: 0.15,
    durationRange: [3900, 6500],
    requiresTarget: false,
    targetType: 'none',
    targetRange: 1,
    interruptible: true,
    tool: null,
  }],
  ['build_farm', {
    type: 'build_farm',
    tags: new Set([ActionTag.BUILD, ActionTag.RESOURCE]),
    baseEnergyCost: 0.25,
    durationRange: [5200, 5200],
    requiresTarget: false,
    targetType: 'none',
    targetRange: 0,
    interruptible: false,
    tool: '🔨',
  }],
  ['seek_mate', {
    type: 'seek_mate',
    tags: new Set([ActionTag.SOCIAL]),
    baseEnergyCost: 0,
    durationRange: [0, 0],
    requiresTarget: true,
    targetType: 'external_cell',
    targetRange: 10,
    interruptible: true,
    tool: null,
  }],
  ['await_mate', {
    type: 'await_mate',
    tags: new Set([ActionTag.SOCIAL]),
    baseEnergyCost: 0.1,
    durationRange: [15000, 20000],
    requiresTarget: false,
    targetType: 'self',
    targetRange: 0,
    interruptible: true,
    tool: null,
  }],
  ['photosynthesize', {
    type: 'photosynthesize',
    tags: new Set([ActionTag.SURVIVAL]),
    baseEnergyCost: 0,
    durationRange: [0, 0],
    requiresTarget: false,
    targetType: 'self',
    targetRange: 0,
    interruptible: true,
    tool: null,
  }],
  ['idle', {
    type: 'idle',
    tags: new Set([]),
    baseEnergyCost: 0,
    durationRange: [250, 250],
    requiresTarget: false,
    targetType: 'none',
    targetRange: 0,
    interruptible: true,
    tool: null,
  }],
]);
