import { ActionTag } from './types';
import type { ActionDef, ActionType } from './types';

/**
 * Static registry of all action definitions.
 * Costs and durations migrated from the old TUNE.actionCost and ACTION_DURATIONS.
 */
export const ACTION_REGISTRY: ReadonlyMap<ActionType, ActionDef> = new Map<ActionType, ActionDef>([
  ['talk', {
    type: 'talk',
    tags: new Set([ActionTag.SOCIAL]),
    energyCost: 0.2,
    durationRange: [2340, 4680],
    requiresTarget: true,
    targetRange: 1,
    interruptible: true,
  }],
  ['quarrel', {
    type: 'quarrel',
    tags: new Set([ActionTag.SOCIAL, ActionTag.COMBAT]),
    energyCost: 0.4,
    durationRange: [2340, 4680],
    requiresTarget: true,
    targetRange: 1,
    interruptible: true,
  }],
  ['attack', {
    type: 'attack',
    tags: new Set([ActionTag.COMBAT]),
    energyCost: 1.1,
    durationRange: [1170, 2340],
    requiresTarget: true,
    targetRange: 2,
    interruptible: false,
  }],
  ['heal', {
    type: 'heal',
    tags: new Set([ActionTag.SOCIAL, ActionTag.HELPFUL]),
    energyCost: 1.5,
    durationRange: [2340, 4680],
    requiresTarget: true,
    targetRange: 1,
    interruptible: true,
  }],
  ['share', {
    type: 'share',
    tags: new Set([ActionTag.SOCIAL, ActionTag.HELPFUL]),
    energyCost: 0.4,
    durationRange: [780, 1300],
    requiresTarget: true,
    targetRange: 1,
    interruptible: true,
  }],
  ['reproduce', {
    type: 'reproduce',
    tags: new Set([ActionTag.SOCIAL]),
    energyCost: 1.5,
    durationRange: [5200, 8320],
    requiresTarget: true,
    targetRange: 1,
    interruptible: false,
  }],
  ['sleep', {
    type: 'sleep',
    tags: new Set([ActionTag.SURVIVAL]),
    energyCost: 0,
    durationRange: [20800, 31200],
    requiresTarget: false,
    targetRange: 0,
    interruptible: true, // Interruptible by attack
  }],
  ['harvest', {
    type: 'harvest',
    tags: new Set([ActionTag.RESOURCE]),
    energyCost: 0.25,
    durationRange: [1560, 3900],
    requiresTarget: false,
    targetRange: 1,
    interruptible: false,
  }],
  ['eat', {
    type: 'eat',
    tags: new Set([ActionTag.SURVIVAL]),
    energyCost: 0,
    durationRange: [780, 1300],
    requiresTarget: false,
    targetRange: 0,
    interruptible: false,
  }],
  ['wash', {
    type: 'wash',
    tags: new Set([ActionTag.SURVIVAL, ActionTag.HYGIENE]),
    energyCost: 0,
    durationRange: [780, 1300],
    requiresTarget: false,
    targetRange: 0,
    interruptible: false,
  }],
  ['deposit', {
    type: 'deposit',
    tags: new Set([ActionTag.RESOURCE, ActionTag.FACTION]),
    energyCost: 0,
    durationRange: [780, 1300],
    requiresTarget: false,
    targetRange: 1,
    interruptible: false,
  }],
  ['withdraw', {
    type: 'withdraw',
    tags: new Set([ActionTag.RESOURCE, ActionTag.FACTION]),
    energyCost: 0,
    durationRange: [780, 1300],
    requiresTarget: false,
    targetRange: 1,
    interruptible: false,
  }],
  ['pickup', {
    type: 'pickup',
    tags: new Set([ActionTag.RESOURCE]),
    energyCost: 0,
    durationRange: [780, 1300],
    requiresTarget: false,
    targetRange: 1,
    interruptible: false,
  }],
  ['poop', {
    type: 'poop',
    tags: new Set([ActionTag.HYGIENE]),
    energyCost: 0,
    durationRange: [1300, 2600],
    requiresTarget: false,
    targetRange: 0,
    interruptible: false,
  }],
  ['clean', {
    type: 'clean',
    tags: new Set([ActionTag.HYGIENE, ActionTag.LEISURE]),
    energyCost: 0.25,
    durationRange: [2080, 3120],
    requiresTarget: false,
    targetRange: 1,
    interruptible: false,
  }],
  ['play', {
    type: 'play',
    tags: new Set([ActionTag.LEISURE]),
    energyCost: 0.15,
    durationRange: [3900, 6500],
    requiresTarget: false,
    targetRange: 1,
    interruptible: true,
  }],
  ['build_farm', {
    type: 'build_farm',
    tags: new Set([ActionTag.BUILD, ActionTag.RESOURCE]),
    energyCost: 0.25,
    durationRange: [5200, 5200],
    requiresTarget: false,
    targetRange: 0,
    interruptible: false,
  }],
]);
